'use strict';

/**
 * Project-aware ACC configuration generation (the `.acc/config/` control
 * plane) + the final "is the repo fully ACC documented?" verification.
 *
 * `acc init` scaffolds only a minimal config.yaml and EMPTY agents/,
 * workflows/, standards/ directories. ABA completes them from the loaded
 * repository so the ACC panel fights with the framework fully configured:
 *
 *   - config.yaml      → every setting the framework reads (mirrors
 *                        acc-agents/lib/config.js DEFAULTS), with language
 *                        analyzers enabled for the languages actually present
 *                        and ignore lists for the repo's build noise.
 *   - agents/default.md → a project-aware default agent profile.
 *   - standards/*.md   → architecture, coding, and review standards.
 *
 * All writes are additive — a repo's own .acc/config/ content is never
 * overwritten, except the minimal config.yaml when ABA just scaffolded it
 * (opts.overwriteConfig).
 */

const fs = require('fs');
const path = require('path');
const { missingContractDirs, missingMemoryFiles } = require('./accfill.cjs');

// Mirrors acc-agents/lib/diagnostics.js ANALYZER_EXTS — keep in sync.
const ANALYZER_EXTS = {
  rust: ['.rs'],
  typescript: ['.ts', '.tsx', '.mts', '.cts'],
  go: ['.go'],
  python: ['.py', '.pyi'],
  java: ['.java'],
  csharp: ['.cs'],
  cpp: ['.c', '.h', '.cpp', '.hpp', '.cc', '.cxx'],
  ruby: ['.rb'],
  php: ['.php'],
  swift: ['.swift'],
  kotlin: ['.kt', '.kts'],
  javascript: ['.js', '.jsx', '.mjs', '.cjs'],
};

// Directories always excluded from ACC walks (VCS, deps, build noise).
const DEFAULT_IGNORE = ['node_modules', 'dist', 'build', 'coverage'];

// Top-level config.yaml settings — mirrors acc-agents/lib/config.js DEFAULTS.
const CONFIG_KEYS = [
  'schema_version',
  'language_analyzers',
  'ignore',
  'diagnostics',
  'ownership',
  'multi_agent',
  'tools',
  'context',
  'graph',
  'memory',
];

/** Recursively list repo-relative file paths, skipping VCS/deps/noise/hidden. */
function walkFiles(root) {
  const out = [];
  const walk = (dir) => {
    let entries;
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of entries) {
      if (e.name === '.git' || e.name === 'node_modules' || e.name === '.acc' || e.name.startsWith('.')) continue;
      if (e.name === 'dist' || e.name === 'build' || e.name === 'coverage') continue;
      const full = path.join(dir, e.name);
      if (e.isDirectory()) walk(full);
      else if (e.isFile()) out.push(path.relative(root, full).split(path.sep).join('/'));
    }
  };
  walk(root);
  return out;
}

/** Language analyzer names for the languages present in the repo. */
function detectLanguages(root) {
  const present = new Set();
  for (const rel of walkFiles(root)) {
    const ext = path.posix.extname(rel).toLowerCase();
    for (const [name, exts] of Object.entries(ANALYZER_EXTS)) {
      if (exts.includes(ext)) {
        present.add(name);
        break;
      }
    }
  }
  return [...present].sort();
}

/** Ignore list for the generated config: standard noise + detected dirs. */
function detectIgnoredDirs(root) {
  const ignore = [...DEFAULT_IGNORE];
  for (const d of ['vendor', 'tmp', 'temp', 'out', 'target', 'venv', '.venv']) {
    if (fs.existsSync(path.join(root, d))) ignore.push(d);
  }
  return ignore;
}

/** Full config.yaml with every supported setting, project-aware. */
function generateConfigYaml(repoName, languages, ignore) {
  const langLines = (languages.length > 0 ? languages : ['rust', 'typescript', 'go', 'python'])
    .map((l) => `  ${l}: true`)
    .join('\n');
  const ignoreLines = ignore.map((d) => `  - ${d}`).join('\n');
  return `# ${repoName} — ACC configuration
#
# Generated by ABA (ACC Battle Arena) from the repository contents so every
# supported setting is present and matches the project. ACC works with
# sensible defaults when a setting is absent; see docs/03-repository-structure.md.
schema_version: 1

# Language analyzers are enabled for the languages actually present in the
# repository (used by acc check / acc graph).
language_analyzers:
${langLines}

# Directories excluded from ACC walks (VCS, dependencies, build noise).
ignore:
${ignoreLines}

diagnostics:
  # Example: downgrade a circular-reference warning to info:
  # warn_only: ["ACC014"]
  warn_only: []

ownership:
  strict: false

multi_agent:
  enabled: false
  max_concurrency: 4
  max_depth: 1
  task_timeout: 300
  resource_limits:
    cpu_percent: 80
    memory_mb: 4096
    token_budget: 1000000
  isolation_mode: git_worktree
  conflict_policy: sequentialize

tools:
  auto_discover: true
  defaults:
    filesystem: true
    search: true
    shell: true
    git: true
    project: true
    context: true
    graph: true
    memory: true
    check: true
  detected:
    enabled: true
  plugins:
    enabled: true
    directory: ".acc/config/tools"
  permissions:
    filesystem:
      read: true
      write: true
      glob: true
    shell:
      enabled: true
      approval: auto
      allowed_commands: []
    git:
      read: true
      write: true
    network:
      enabled: false

context:
  default_depth: 1
  default_max_bytes: 65536

graph:
  default_format: text
  default_provenance: true

memory:
  warn_bytes: 65536
  timestamp_format: rfc3339
`;
}

// Control-plane directories the docs list beyond agents/workflows/standards,
// each with a README documenting what belongs there.
const CONTROL_PLANE_DIRS = {
  skills: `# skills/ — ACC-Managed Skills

SKILL.md packages (Agent Skills standard) that this project makes available
\nto agents. Each skill lives in its own subdirectory:

    skills/<skill-name>/
    ├── SKILL.md
    └── references/

Skills are reusable capability definitions agents can opt in to use; the
durable knowledge about this project lives in each functionality's
AGENTS.md and .acc-memory.md, not in the skill definitions.
`,
  mcp: `# mcp/ — MCP Bridge Definitions

Definitions of ACC bridges to external services (GitHub API, LLM providers,
\netc.), referencing standard MCP server configurations rather than
\nredefining them:

    mcp/<bridge-name>/
    ├── plugin.yaml
    └── index.js

MCP configurations define how agents communicate with external services;
the repository's knowledge stays local.
`,
  tools: `# tools/ — Tool Plugins

External tooling plugins available to agents in this project:

    tools/<plugin-name>/
    ├── plugin.yaml
    └── index.js

Plugins are declared here and enabled via the \`tools\` section of
\`.acc/config/config.yaml\` (\`tools.plugins.directory\` points here).
`,
  'multi-agent': `# multi-agent/ — Orchestration Configuration

Multi-agent orchestration configuration for this project. The active
\nsettings live in config.yaml under the \`multi_agent\` section
\n(\`enabled: false\` by default); per-mode overrides can live in this
\ndirectory.
`,
};



/** agents/default.md — project-aware default agent profile. */
function agentProfile(repoName, languages) {
  return `# default.md — Default Agent Profile

Agent profile for a coding agent working in ${repoName}.

## Operating rules

1. **Start from the contracts.** Read the root AGENTS.md, then the AGENTS.md
   of the functionality you are working in, before editing anything.
2. **Follow the control plane.** Procedures live in
   \`.acc/config/workflows/\`; standards in \`.acc/config/standards/\`.
3. **Use the acc CLI for focused context.** \`acc context <dir>\`,
   \`acc graph\`, \`acc dependencies <dir>\`, \`acc impact <dir>\`.
4. **Record durable knowledge.** After significant work, run
   \`acc memory add <dir> "<what you learned>"\`.
5. **Validate before finishing.** Run \`acc check\` and fix every
   error-level diagnostic.

## Project facts

- Name: ${repoName}
- Languages: ${languages.length > 0 ? languages.join(', ') : 'n/a'}
- Every functionality directory carries its own AGENTS.md contract and
  .acc-memory.md log.
`;
}

/** standards/*.md — project-aware architecture, coding, and review docs. */
function standardsDocs(repoName, languages) {
  const langs = languages.length > 0 ? languages.join(', ') : 'n/a';
  return {
    'architecture.md': `# architecture.md — Architecture Standards

${repoName} is organized as ACC functionality boundaries: each meaningful
directory owns an AGENTS.md contract declaring its purpose, ownership,
dependencies, and constraints. The derived architecture graph
(\`acc graph\`) is the authoritative map of boundaries and relationships.

## Rules

- A functionality's code lives in its own directory, documented by that
  directory's AGENTS.md.
- Cross-boundary dependencies are declared in the Dependencies section of
  the source boundary's contract.
- New boundaries follow \`.acc/config/workflows/feature.md\`; structural
  changes follow \`.acc/config/workflows/refactor.md\`.
`,
    'coding.md': `# coding.md — Coding Standards

Coding standards for ${repoName} (languages: ${langs}).

## Rules

- Match the existing style of the file you edit.
- Prefer small, single-purpose functions and modules.
- Do not introduce dependencies that are not declared in the boundary's
  AGENTS.md Dependencies section.
- Never commit secrets, credentials, or build artifacts.
- Update the relevant AGENTS.md when behavior or boundaries change.
`,
    'review.md': `# review.md — Review Checklist

Review checklist for changes to ${repoName}.

## Checklist

- [ ] \`acc check\` passes with zero error-level diagnostics.
- [ ] Every changed functionality's AGENTS.md reflects the new behavior,
      ownership, and dependencies.
- [ ] Durable knowledge was recorded with
      \`acc memory add <dir> "..."\`.
- [ ] The project's own tests/build pass.
- [ ] No secrets, build artifacts, or large binaries are committed.
`,
  };
}

/**
 * Write the complete .acc/config/ set (additive). Returns
 * { config, agents, standards, languages, ignore }.
 */
function writeAccConfig(root, repoName, opts = {}) {
  const configDir = path.join(root, '.acc', 'config');
  fs.mkdirSync(configDir, { recursive: true });
  const result = {
    config: false,
    agents: [],
    standards: [],
    languages: detectLanguages(root),
    ignore: detectIgnoredDirs(root),
  };

  // config.yaml — replaced only when ABA just scaffolded it (opts.overwriteConfig).
  const configFile = path.join(configDir, 'config.yaml');
  if (opts.overwriteConfig || !fs.existsSync(configFile)) {
    fs.writeFileSync(configFile, generateConfigYaml(repoName, result.languages, result.ignore), 'utf8');
    result.config = true;
  }

  const agentsDir = path.join(configDir, 'agents');
  fs.mkdirSync(agentsDir, { recursive: true });
  const profileFile = path.join(agentsDir, 'default.md');
  if (!fs.existsSync(profileFile)) {
    fs.writeFileSync(profileFile, agentProfile(repoName, result.languages), 'utf8');
    result.agents.push('default.md');
  }

  const standardsDir = path.join(configDir, 'standards');
  fs.mkdirSync(standardsDir, { recursive: true });
  for (const [name, content] of Object.entries(standardsDocs(repoName, result.languages))) {
    const f = path.join(standardsDir, name);
    if (!fs.existsSync(f)) {
      fs.writeFileSync(f, content, 'utf8');
      result.standards.push(name);
    }
  }

  // The docs' full control plane also has skills/, mcp/, tools/, and
  // multi-agent/ — scaffold each with a README documenting its purpose.
  result.controlPlane = [];
  for (const [name, readme] of Object.entries(CONTROL_PLANE_DIRS)) {
    const dir = path.join(configDir, name);
    fs.mkdirSync(dir, { recursive: true });
    const f = path.join(dir, 'README.md');
    if (!fs.existsSync(f)) {
      fs.writeFileSync(f, readme, 'utf8');
      result.controlPlane.push(name);
    }
  }

  return result;
}

/**
 * Verify the repo is FULLY ACC documented. Returns a list of problems
 * (empty = complete). Checks: config present with every setting, agents/
 * standards/ workflows/ populated, every content folder contracted, every
 * contract complete (acc fill), every contract with a filled memory file.
 */
async function verifyAccDocumented(root, runAcc) {
  const problems = [];

  // 1. Control plane files.
  const configFile = path.join(root, '.acc', 'config', 'config.yaml');
  if (!fs.existsSync(configFile)) {
    problems.push('.acc/config/config.yaml is missing');
  } else {
    let text = '';
    try {
      text = fs.readFileSync(configFile, 'utf8');
    } catch {
      text = '';
    }
    for (const key of CONFIG_KEYS) {
      if (!text.includes(`${key}:`)) problems.push(`config.yaml is missing the '${key}' setting`);
    }
  }
  for (const dir of ['agents', 'standards', 'workflows', 'skills', 'mcp', 'tools', 'multi-agent']) {
    const d = path.join(root, '.acc', 'config', dir);
    let hasMd = false;
    try {
      hasMd = fs.readdirSync(d).some((f) => f.endsWith('.md'));
    } catch {
      hasMd = false;
    }
    if (!hasMd) problems.push(`.acc/config/${dir}/ has no files`);
  }


  // 2. Every content folder has a contract.
  const missingDirs = missingContractDirs(root);
  for (const dir of missingDirs) problems.push(`${dir} lacks an AGENTS.md contract`);

  // 3. Every contract is complete (no placeholders).
  const fill = await runAcc(['fill', '--json'], root);
  try {
    const summary = JSON.parse(fill.out).result?.summary;
    if (summary && summary.draft > 0) {
      problems.push(`${summary.draft} AGENTS.md contract${summary.draft === 1 ? '' : 's'} still incomplete`);
    }
  } catch {
    // non-JSON output — fall through
  }

  // 4. Every contract has a filled .acc-memory.md.
  const missingMemory = missingMemoryFiles(root);
  if (missingMemory.length > 0) {
    problems.push(`${missingMemory.length} contract${missingMemory.length === 1 ? '' : 's'} lack a filled .acc-memory.md`);
  }

  return problems;
}

module.exports = {
  ANALYZER_EXTS,
  CONFIG_KEYS,
  CONTROL_PLANE_DIRS,
  detectLanguages,
  detectIgnoredDirs,
  generateConfigYaml,
  writeAccConfig,
  verifyAccDocumented,
};
